version: "3.2"

services:
  madara:
    image: ghcr.io/keep-starknet-strange/madara:latest
    ports:
      - "9615:9615"
      - "9944:9944"
      - "30333:30333"
    command:
      - "--rpc-external"
      - "--rpc-methods=unsafe"
      - "--dev"
    networks:
      - internal

  madara-app:
    image: ghcr.io/keep-starknet-strange/madara-app:latest
    ports:
      - "8080:80"
    environment:
      WS_URL: "ws://127.0.0.1:9944"

  starkcet-front:
    image: ghcr.io/zizou0x/starkcet-frontend:latest
    ports:
      - 3001:3000
    depends_on:
      - starkcet-back
    networks:
      - internal

  starkcet-back:
    image: ghcr.io/zizou0x/starkcet-backend:latest
    environment:
      - PRIVATE_KEY=0x00c1cf1490de1352865301bb8705143f3ef938f97fdf892f1090dcb5ac7bcd1d
      - STARKNET_ACCOUNT_ADDRESS=0x2
      - TOKEN_ADDRESS=0x49d36570d4e46f48e99674bd3fcc84644ddd6b96f7c741b1562b82f9e004dc7
      - RPC_URL=${RPC_URL}
      - AMOUNT_TRANSFERED=1000000000000000
    restart: on-failure
    depends_on:
      - madara
    networks:
      - internal

  misc-apps:
    build:
      context: misc-apps/
      dockerfile: Dockerfile
    depends_on:
      - madara
    environment:
      - RPC_URL=${RPC_URL}
      - STARKNET_NETWORK=${STARKNET_NETWORK}
    volumes:
      - ./deployments:/app/kakarot/deployments/${STARKNET_NETWORK}
    networks:
      - internal

  kakacet-front:
    image: ghcr.io/kkrt-labs/kakacet/frontend:latest
    restart: on-failure
    ports:
      - 3002:3000
    depends_on:
      - starkcet-back
    networks:
      - internal

  kakarot-rpc:
    build:
      dockerfile: misc-apps/kakarot/Dockerfile
    ports:
      - 9545:9545
    command: ["./run.sh", "/usr/bin/tini", "--", "/usr/local/bin/kakarot-rpc"]
    environment:
      - STARKNET_NETWORK=${STARKNET_NETWORK}
      - SHARINGAN_RPC_URL=${RPC_URL}
      - RUST_LOG=trace
    volumes:
      -  ./deployments:/usr/src/app/deployments
    depends_on:
      misc-apps:
        condition: service_completed_successfully # wait for misc-apps to deploy contracts
    restart: on-failure
    networks:
      - internal

# blocked while no arm64
#  apibara:
#    image: quay.io/apibara/starknet:7f00306001c1ff030ccc1babf49b880dbe6c7e0e 
#    ports:
#      - 7171:7171
#    command:
#      - start
#    environment:
#      - RPC=http://madara:9944
#      - WAIT_FOR_RPC=true
#      - RUST_LOG=warn
#    restart: on-failure
#    depends_on:
#      - madara
#    networks:
#      - internal

networks:
  internal:
